import java.util.*;

public class Main {
    public static void main(String[] args) {

        // Load data
        Map<String, Airport> airports = Data.loadAirports();
        List<Flight> hotFlights = Data.loadflights(airports);

        // Build graph
        FlightGraph graph = new FlightGraph();
        for (Airport a : airports.values()) {
            graph.addAirport(a);
        }
        for (Flight f : hotFlights) {
            graph.addFlight(f);
        }

        // Initialize components
        RouteFinder finder = new RouteFinder(graph);
        ReservationManager reservationManager = new ReservationManager(hotFlights);

        // ========== SAMPLE SCENARIOS ==========
        System.out.println("=== DYNAMIC FLIGHT PRICING SYSTEM HARDCODED DEMO ===\n");

        // SAMPLE 1: Find route from Athens to Berlin
        System.out.println("--- SAMPLE 1: Route Finding (BFS) ---");
        System.out.println("Finding route: Athens (ATH) to Berlin (BER)");
        Airport departure = airports.get("ATH");
        Airport arrival = airports.get("BER");
        List<Airport> route = finder.BFS(departure, arrival);
        finder.printRoute(route);
        finder.printDetails(route, "NO");

        // SAMPLE 2: Find a longer route - Athens to Reykjavik
        System.out.println("\n--- SAMPLE 2: Long Route ---");
        System.out.println("Finding route: Athens (ATH) to Reykjavik (KEF)");
        Airport reykjavik = airports.get("KEF");
        List<Airport> longRoute = finder.BFS(departure, reykjavik);
        finder.printRoute(longRoute);
        finder.printDetails(longRoute, "NO");

        // SAMPLE 3: Dynamic pricing demonstration
        System.out.println("\n--- SAMPLE 3: Dynamic Pricing ---");
        System.out.println("Showing how prices change based on seat availability.\n");

        // Find a direct flight to demonstrate pricing
        Flight demoFlight = null;
        for (Flight f : hotFlights) {
            if (f.getId().equals("FL99")) {
                demoFlight = f;
                break;
            }
        }

        if (demoFlight != null) {
            // Set initial distance and price
            double distance = DistanceCalculator.getDistance(demoFlight.getDeparture(), demoFlight.getArrival());
            demoFlight.setDistance(distance);
            double initialPrice = PriceCalculator.price(demoFlight, distance);
            demoFlight.setPrice(initialPrice);

            System.out.println("Flight FL99: " + demoFlight.getDeparture().getCityCode() + " -> " + demoFlight.getArrival().getCityCode());
            System.out.println("Before reservations:");
            System.out.printf("  Seats: %d/%d | Price: %.2f Euros%n",
                demoFlight.getSeatsTaken(), demoFlight.getCapacity(), demoFlight.getPrice());

            // Make 10 reservations
            System.out.println("\n10 reservations being made on FL99");
            for (int i = 0; i < 10; i++) {
                reservationManager.reserve("FL99");
            }

            System.out.println("\nAfter the reservations:");
            System.out.printf("  Seats: %d/%d | Price: %.2f Euros%n",
                demoFlight.getSeatsTaken(), demoFlight.getCapacity(), demoFlight.getPrice());
            System.out.println("Price increased due to reduced seat availability!");
        }

        // SAMPLE 4: Show all direct flights from Athens
        System.out.println("\n--- SAMPLE 4: Direct Flights from Athens ---");
        List<Flight> athensFlights = graph.getFlights(airports.get("ATH"));
        finder.printFromDeparture(athensFlights, "NO");

        // SAMPLE 5: Performance measurement with different data set sizes
        System.out.println("\n--- SAMPLE 5: Performance Measurement (BFS Algorithm) ---");
        System.out.println("Testing BFS with different graph sizes (100, 1000, 10000 airports)\n");
        performanceTest();

        System.out.println("\n=== END OF SAMPLES ===");


        ////////////////////
        Scanner read = new Scanner(System.in);

        while (true) {
            System.out.println("Would you like to see an optional menu about flights? yes/no");
            String specific = read.nextLine().toLowerCase();
            if (specific.equals("yes")) {
                Menu.menu(airports, finder);
                break;
            }
            if (specific.equals("no")) {
                break;
            } else
                System.out.println("Wrong input.");
        }
        System.out.println("Program Terminates.");




        ///////////////////

    }

    /**
     * AI-GENERATED METHOD
     * This method was generated by Claude AI to create synthetic test data
     * for performance measurement, as permitted by the assignment guidelines.
     *
     * Tests BFS algorithm performance with different graph sizes (100, 1000, 10000 airports).
     */
    private static void performanceTest() {
        int[] sizes = {100, 1000, 10000};

        for (int size : sizes) {
            // Generate test data
            List<Airport> testAirports = new ArrayList<>();
            FlightGraph testGraph = generateTestGraph(size, testAirports);

            // Get first and last airport for BFS test
            Airport from = testAirports.get(0);
            Airport to = testAirports.get(testAirports.size() - 1);

            RouteFinder testFinder = new RouteFinder(testGraph);

            // Measure BFS execution time
            long startTime = System.nanoTime();
            testFinder.BFS(from, to);
            long endTime = System.nanoTime();

            double timeMs = (endTime - startTime) / 1_000_000.0;
            System.out.printf("Graph size: %5d airports | BFS time: %.4f ms%n", size, timeMs);
        }
    }

    /**
     * AI-GENERATED METHOD
     * This method was generated by Claude AI to create synthetic test data
     * for performance measurement, as permitted by the assignment guidelines.
     *
     * Generates a FlightGraph with the specified number of airports and
     * random flight connections between them.
     *
     * @param numAirports The number of airports to generate
     * @param airportList An empty list that will be populated with the generated airports
     * @return A FlightGraph containing the generated airports and flights
     */
    private static FlightGraph generateTestGraph(int numAirports, List<Airport> airportList) {
        FlightGraph graph = new FlightGraph();
        Random random = new Random(42); // Fixed seed for reproducible results

        // Generate synthetic airports with random coordinates
        for (int i = 0; i < numAirports; i++) {
            double lat = -90 + (random.nextDouble() * 180);  // Latitude: -90 to 90
            double lon = -180 + (random.nextDouble() * 360); // Longitude: -180 to 180
            Airport airport = new Airport("A" + i, "City" + i, lat, lon);
            airportList.add(airport);
            graph.addAirport(airport);
        }

        // Generate random flights - each airport connects to ~5 other airports
        int flightId = 0;
        for (int i = 0; i < numAirports; i++) {
            int connections = 3 + random.nextInt(5); // 3-7 connections per airport
            for (int j = 0; j < connections; j++) {
                int targetIndex = random.nextInt(numAirports);
                if (targetIndex != i) {
                    Flight flight = new Flight("TF" + flightId++, airportList.get(i), airportList.get(targetIndex));
                    graph.addFlight(flight);
                }
            }
        }

        return graph;
    }
}
